// Morning Cockpit prioritisation. Deliberately simple, deliberately NOT an
// AI ranking model (Step 19) — it reads the already-persisted, evidence-
// backed `insights` rows (generated by services/insight-rules.ts) plus open
// recommendations, and applies a small set of documented rules. Replacing
// this function later with a smarter model doesn't require touching the
// schema or the Cockpit UI, only this file.
import { getSupabaseClient } from "@/lib/supabase/server"
import type { Client, Insight, InsightEvidence, Recommendation } from "@/lib/supabase/types"
import type { Priority } from "@/lib/types"
import { getClientCreditFacilities } from "./credit"
import { getClientHoldings } from "./portfolios"
import { getClientPlannedCashNeeds } from "./planning"
import { getAverageHandlingTimeByClient } from "./recommendations"
import { concentrationByRegion } from "@/lib/portfolio-analytics"
import type { SourceSystem } from "@/lib/data"

const SOURCE_BY_INSIGHT_TYPE: Record<Insight["insight_type"], SourceSystem> = {
  CREDIT_RISK: "Credit Facility",
  CONCENTRATION_RISK: "Holdings",
  LIQUIDITY_GAP: "CRM",
  MANDATE_BREACH: "Mandate",
  BEHAVIOURAL_SIGNAL: "RM Note",
  LIFE_EVENT: "CRM",
  MARKET_EVENT_IMPACT: "Advice Ledger",
}

const SEVERITY_SCORE: Record<Insight["severity"], number> = { Critical: 4, High: 3, Medium: 2, Low: 1 }

const NEXT_ACTION_BY_TYPE: Record<Insight["insight_type"], string> = {
  CREDIT_RISK: "Review collateral and funding options today.",
  CONCENTRATION_RISK: "Discuss diversification away from the concentrated exposure.",
  MANDATE_BREACH: "Begin suitability and mandate review.",
  LIQUIDITY_GAP: "Review liquidity plan against upcoming cash needs.",
  BEHAVIOURAL_SIGNAL: "Review recent RM notes before the next contact.",
  LIFE_EVENT: "Plan around the upcoming life event.",
  MARKET_EVENT_IMPACT: "Assess portfolio impact of the recent market event.",
}

export interface CockpitEvidenceItem {
  label: string
  value: string
  source: SourceSystem
}

export interface CockpitClient {
  client: Client
  priority: Priority
  reason: string
  evidence: CockpitEvidenceItem[]
  exposureLabel: string
  exposureValue: string
  nextAction: string
  previousAdvice: { status: Recommendation["status"]; summary: string; date: string } | null
  primaryInsight: (Insight & { evidence: InsightEvidence[] }) | null
  avgHandlingTimeHours: number | null
}

export function classifyPriority(severity: Insight["severity"] | null, hasOpenRecommendation: boolean): Priority | null {
  if (severity === "Critical" || severity === "High") return "ACTION REQUIRED"
  if (severity === "Medium") return "RM CHECK-IN"
  if (severity === "Low") return "REVIEW"
  if (hasOpenRecommendation) return "FOLLOW-UP"
  return null
}

async function buildEvidence(clientId: string, insight: Insight): Promise<CockpitEvidenceItem[]> {
  const source = SOURCE_BY_INSIGHT_TYPE[insight.insight_type]
  const values = await buildEvidenceValues(clientId, insight)
  return values.map((v) => ({ ...v, source }))
}

async function buildEvidenceValues(clientId: string, insight: Insight): Promise<{ label: string; value: string }[]> {
  switch (insight.insight_type) {
    case "CREDIT_RISK": {
      const facilities = await getClientCreditFacilities(clientId)
      const facility = facilities.find((f) => insight.title.includes(f.facility_type ?? "")) ?? facilities[0]
      if (!facility?.latest) return []
      return [
        { label: "Current LTV", value: `${facility.latest.ltv_pct?.toFixed(2)}%` },
        { label: "Margin call threshold", value: `${facility.margin_call_ltv_pct?.toFixed(2)}%` },
        { label: "Drawn", value: `${facility.latest.drawn?.toLocaleString()} ${facility.facility_ccy}` },
        { label: "Headroom", value: `${(facility.latest.headroom ?? 0).toLocaleString()} ${facility.facility_ccy}` },
      ]
    }
    case "CONCENTRATION_RISK": {
      const holdings = await getClientHoldings(clientId)
      const top = concentrationByRegion(holdings)[0]
      if (!top) return []
      return [
        { label: "Region", value: top.label },
        { label: "Concentration", value: `${top.pct.toFixed(1)}%` },
        { label: "Value", value: `USD ${(top.valueUsd / 1e6).toFixed(1)}m` },
      ]
    }
    case "LIQUIDITY_GAP": {
      const needs = await getClientPlannedCashNeeds(clientId)
      const next = needs[0]
      if (!next) return []
      return [
        { label: "Next cash need", value: next.description ?? "" },
        { label: "Amount", value: `${next.amount?.toLocaleString()} ${next.currency}` },
        { label: "Due", value: `${next.due_from} – ${next.due_to}` },
      ]
    }
    case "MANDATE_BREACH":
      return [{ label: "Signal", value: insight.title }]
    default:
      return [{ label: "Signal", value: insight.title }]
  }
}

export async function getCockpitClients(): Promise<CockpitClient[]> {
  const supabase = getSupabaseClient()

  const [
    { data: clients, error: clientsError },
    { data: insights, error: insightsError },
    { data: recs, error: recsError },
    avgHandlingTimeByClient,
  ] = await Promise.all([
    supabase.from("clients").select("*"),
    supabase.from("insights").select("*").eq("status", "OPEN"),
    supabase
      .from("recommendations")
      .select("*")
      .in("status", ["DRAFT", "READY_FOR_REVIEW", "APPROVED", "DEFERRED"]),
    getAverageHandlingTimeByClient(),
  ])

  if (clientsError) throw new Error(`getCockpitClients clients: ${clientsError.message}`)
  if (insightsError) throw new Error(`getCockpitClients insights: ${insightsError.message}`)
  if (recsError) throw new Error(`getCockpitClients recommendations: ${recsError.message}`)

  const insightsByClient = new Map<string, Insight[]>()
  for (const insight of insights as Insight[]) {
    const list = insightsByClient.get(insight.client_id) ?? []
    list.push(insight)
    insightsByClient.set(insight.client_id, list)
  }

  const recsByClient = new Map<string, Recommendation[]>()
  for (const rec of recs as Recommendation[]) {
    const list = recsByClient.get(rec.client_id) ?? []
    list.push(rec)
    recsByClient.set(rec.client_id, list)
  }

  const results: CockpitClient[] = []

  for (const client of clients as Client[]) {
    const clientInsights = insightsByClient.get(client.client_id) ?? []
    const clientRecs = recsByClient.get(client.client_id) ?? []

    const primaryInsightBase = [...clientInsights].sort(
      (a, b) => SEVERITY_SCORE[b.severity] - SEVERITY_SCORE[a.severity],
    )[0]

    const priority = classifyPriority(primaryInsightBase?.severity ?? null, clientRecs.length > 0)
    if (!priority) continue

    const deferred = clientRecs.find((r) => r.status === "DEFERRED")

    const evidence = primaryInsightBase ? await buildEvidence(client.client_id, primaryInsightBase) : []

    results.push({
      client,
      priority,
      reason: primaryInsightBase?.summary ?? clientRecs[0]?.rationale ?? clientRecs[0]?.recommendation ?? "Open recommendation awaiting review.",
      evidence,
      exposureLabel: "Relationship value",
      exposureValue: client.total_aum_usd
        ? `${client.base_currency ?? "USD"} ${(client.total_aum_usd / 1e6).toFixed(1)}m`
        : "—",
      nextAction: primaryInsightBase
        ? NEXT_ACTION_BY_TYPE[primaryInsightBase.insight_type]
        : "Review open recommendation.",
      previousAdvice: deferred
        ? { status: deferred.status, summary: deferred.title, date: new Date(deferred.created_at).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" }) }
        : null,
      primaryInsight: primaryInsightBase ? { ...primaryInsightBase, evidence: [] } : null,
      avgHandlingTimeHours: avgHandlingTimeByClient.get(client.client_id) ?? null,
    })
  }

  const priorityRank: Record<Priority, number> = { "ACTION REQUIRED": 0, "RM CHECK-IN": 1, "FOLLOW-UP": 2, REVIEW: 3 }
  results.sort((a, b) => {
    const rankDiff = priorityRank[a.priority] - priorityRank[b.priority]
    if (rankDiff !== 0) return rankDiff
    return (b.client.total_aum_usd ?? 0) - (a.client.total_aum_usd ?? 0)
  })

  return results
}
